### ISSUE TITLE
The old repo URL should redirect to the new repo URL

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa-frames#103]
https://github.com/adamamer20/mesa-frames should automatically redirect to https://github.com/projectmesa/mesa-frames. I have seen in the past that this is doable. Currently, my open tabs show HTTP 404 due to the issues, discussions, and pull requests are transferred to this repo.

**Comment by adamamer20** [comment]
> https://github.com/adamamer20/mesa-frames should automatically redirect to https://github.com/projectmesa/mesa-frames. I have seen in the past that this is doable. Currently, my open tabs show HTTP 404 due to the issues, discussions, and pull requests are transferred to this repo.

Redirection used to work. The problem is that I forked the projectmesa repository on my account I think. I'll delete the fork.
