### ISSUE TITLE
mesa-frames license

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-frames#94]
@projectmesa/maintainers, this repo is currently licenced MIT, while our other repos are licensed Apache 2.0. We should discuss if we want to sync that one way or another, or that we want to keep to keep it this way

@adamamer20 you of course also have a heavy say in this.

**Comment by adamamer20** [comment]
I think it's better for this repo to also be licensed with Apache 2.0 for clarity. Any permissive free software licence is ok for me.

**Comment by jackiekazil** [comment]
This is a great catch and call out! We have purposefully selected Apache 2.0 early in the project after much discussion. Let's keep things Apache 2.0.
